In [7]:
import numpy as np
import pandas as pd
from viz import show_field
from GeneticSolver import GeneticSolver
from MPGeneticSolver import MPGeneticSolver

In [2]:
df = pd.read_csv('resources/train.csv', index_col='id')
sample = df[df.delta == 3].sample(random_state=42)
X, Y = sample.values[:, 1:401].reshape((20, 20)), sample.values[:, 401:].reshape((20, 20))

In [13]:
gs_etalon = GeneticSolver(random_state=42, verbosity=1, n_generations=100)

In [14]:
gs_etalon.solve(Y, 3)

Generation #: best score
Generation 1: 0.75
Generation 2: 0.76
Generation 3: 0.76
Generation 4: 0.76
Generation 5: 0.76
Generation 6: 0.76
Generation 7: 0.76
Generation 8: 0.76
Generation 9: 0.76
Generation 10: 0.76
Generation 11: 0.7775
Generation 12: 0.7775
Generation 13: 0.7775
Generation 14: 0.7775
Generation 15: 0.7775
Generation 16: 0.7775
Generation 17: 0.7775
Generation 18: 0.7775
Generation 19: 0.7775
Generation 20: 0.7775
Generation 21: 0.7775
Generation 22: 0.78
Generation 23: 0.78
Generation 24: 0.78
Generation 25: 0.7825
Generation 26: 0.7825
Generation 27: 0.7825
Generation 28: 0.7825
Generation 29: 0.7825
Generation 30: 0.7825
Generation 31: 0.7975
Generation 32: 0.7975
Generation 33: 0.7975
Generation 34: 0.7975
Generation 35: 0.7975
Generation 36: 0.7975
Generation 37: 0.7975
Generation 38: 0.7975
Generation 39: 0.8
Generation 40: 0.8
Generation 41: 0.8
Generation 42: 0.8
Generation 43: 0.8
Generation 44: 0.8
Generation 45: 0.8
Generation 46: 0.8
Generation 47: 0.8
Gen

(array([[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1],
        [0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0,

In [15]:
gs_lower_mutation = GeneticSolver(random_state=42, verbosity=1, n_generations=100, mutate_chance=0.02)
gs_lower_mutation.solve(Y, 3)

Generation #: best score
Generation 1: 0.745
Generation 2: 0.745
Generation 3: 0.745
Generation 4: 0.755
Generation 5: 0.7625
Generation 6: 0.7625
Generation 7: 0.7625
Generation 8: 0.7625
Generation 9: 0.7625
Generation 10: 0.7625
Generation 11: 0.7675
Generation 12: 0.7675
Generation 13: 0.7675
Generation 14: 0.7675
Generation 15: 0.7675
Generation 16: 0.785
Generation 17: 0.785
Generation 18: 0.785
Generation 19: 0.785
Generation 20: 0.785
Generation 21: 0.785
Generation 22: 0.785
Generation 23: 0.785
Generation 24: 0.785
Generation 25: 0.785
Generation 26: 0.79
Generation 27: 0.79
Generation 28: 0.795
Generation 29: 0.795
Generation 30: 0.795
Generation 31: 0.795
Generation 32: 0.795
Generation 33: 0.795
Generation 34: 0.795
Generation 35: 0.795
Generation 36: 0.795
Generation 37: 0.8
Generation 38: 0.8
Generation 39: 0.8
Generation 40: 0.8
Generation 41: 0.8
Generation 42: 0.8
Generation 43: 0.8
Generation 44: 0.8
Generation 45: 0.8
Generation 46: 0.8025
Generation 47: 0.8025
Gene

(array([[0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
        [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
        [1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0,

In [16]:
gs_higher_mutation = GeneticSolver(random_state=42, verbosity=1, n_generations=100, mutate_chance=0.2)
gs_higher_mutation.solve(Y, 3)

Generation #: best score
Generation 1: 0.745
Generation 2: 0.745
Generation 3: 0.745
Generation 4: 0.745
Generation 5: 0.745
Generation 6: 0.745
Generation 7: 0.745
Generation 8: 0.745
Generation 9: 0.745
Generation 10: 0.745
Generation 11: 0.745
Generation 12: 0.745
Generation 13: 0.745
Generation 14: 0.745
Generation 15: 0.745
Generation 16: 0.745
Generation 17: 0.745
Generation 18: 0.745
Generation 19: 0.745
Generation 20: 0.765
Generation 21: 0.765
Generation 22: 0.765
Generation 23: 0.765
Generation 24: 0.765
Generation 25: 0.765
Generation 26: 0.765
Generation 27: 0.765
Generation 28: 0.765
Generation 29: 0.765
Generation 30: 0.765
Generation 31: 0.765
Generation 32: 0.765
Generation 33: 0.765
Generation 34: 0.765
Generation 35: 0.765
Generation 36: 0.765
Generation 37: 0.765
Generation 38: 0.765
Generation 39: 0.765
Generation 40: 0.765
Generation 41: 0.765
Generation 42: 0.765
Generation 43: 0.765
Generation 44: 0.765
Generation 45: 0.765
Generation 46: 0.765
Generation 47: 0.7

(array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
        [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 0, 0,

In [17]:
gs_higher_mutation = GeneticSolver(random_state=42, verbosity=1, n_generations=100, mutate_chance=0.5)
gs_higher_mutation.solve(Y, 3)

Generation #: best score
Generation 1: 0.745
Generation 2: 0.745
Generation 3: 0.745
Generation 4: 0.745
Generation 5: 0.745
Generation 6: 0.745
Generation 7: 0.745
Generation 8: 0.745
Generation 9: 0.745
Generation 10: 0.745
Generation 11: 0.745
Generation 12: 0.745
Generation 13: 0.745
Generation 14: 0.745
Generation 15: 0.745
Generation 16: 0.745
Generation 17: 0.745
Generation 18: 0.745
Generation 19: 0.745
Generation 20: 0.745
Generation 21: 0.745
Generation 22: 0.745
Generation 23: 0.745
Generation 24: 0.745
Generation 25: 0.745
Generation 26: 0.745
Generation 27: 0.745
Generation 28: 0.745
Generation 29: 0.745
Generation 30: 0.745
Generation 31: 0.745
Generation 32: 0.745
Generation 33: 0.745
Generation 34: 0.745
Generation 35: 0.745
Generation 36: 0.745
Generation 37: 0.745
Generation 38: 0.745
Generation 39: 0.755
Generation 40: 0.755
Generation 41: 0.755
Generation 42: 0.755
Generation 43: 0.755
Generation 44: 0.755
Generation 45: 0.755
Generation 46: 0.755
Generation 47: 0.7

(array([[1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1],
        [1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1],
        [0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0],
        [1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
        [1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0],
        [1, 1, 1, 0,